自動更新機能
zumi-n/chat-space pull request #24
Opened 2019-04-07 12:23 UTC by zumi-n

2019-04-07 12:30 UTC, zumi-n commented
#WHAT
自動更新機能
https://gyazo.com/311114d42f9aa354d291d9914e6a1218

#WHY
カリキュラムのため

2019-04-07 12:35 UTC, yuki-uchida requested changes

2019-04-07 12:35 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +    if (message.content && message.image) {
こちら、書き方が少し冗長なので、
HTMLのなかに変数を埋め込む形で対応しましょう。
div
imageHTML
div
のような形です
imageHTMLの中身がif文で分けられていれば、非常に短くかけます

2019-04-07 12:35 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +    .done(function(data){
dataよりも具体的な名前で書きましょう

2019-04-07 12:55 UTC, zumi-n commented on app/assets/javascripts/message.js
> +    .done(function(data){
messageに変更致しました。

2019-04-08 02:27 UTC, kuroko918 commented on Gemfile
> +gem 'pry-rails'
こちらはdevelopment環境でしか使用しないので、`group :development do`の中に入れておいてください。

2019-04-08 02:43 UTC, zumi-n commented on Gemfile
> +gem 'pry-rails'
group :development doの中に入れる修正行いました。

2019-04-08 02:46 UTC, miyagit commented on app/views/messages/index.json.jbuilder
> +  json.array! @new_messages.all do |message|
.allはひつようでしょうか？？

2019-04-08 03:46 UTC, zumi-n commented on app/views/messages/index.json.jbuilder
> +  json.array! @new_messages.all do |message|
なくても動きますので削除しました。

2019-04-08 03:49 UTC, kuroko918 commented
いいかと思います！
LGTMです。

2019-04-08 06:29 UTC, merged